before_commands:
    - "composer install --no-dev --prefer-source"

tools:
    external_code_coverage:
        enabled: true
        timeout: 500
        filter:
            excluded_paths: ["build", "config", "tests", "vendor"]
    php_code_coverage:
        enabled: false
        test_command: phpunit -c phpunit.xml.dist
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["build", "config", "tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
            fixers:
                indentation: true
                linefeed: true
                trailing_spaces: true
                unused_use: true
                phpdoc_params: true
                visibility: true
                return: true
                short_tag: false
                braces: true
                include: true
                php_closing_tag: true
                extra_empty_lines: true
                controls_spaces: true
                elseif: true
                eof_ending: true
        filter:
            paths: ["src/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["build", "config", "tests", "vendor"]
    php_mess_detector:
        enabled: true
        config:
            ruleset: phpmd.xml.dist
            design_rules: { eval_expression: false }
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["build", "config", "tests", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]
    sensiolabs_security_checker: true