language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
  allow_failures:
    - php: 7
    - php: hhvm

notifications:
  email: "siad.ardroumli@gmail.com"

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source
  - mkdir -p build/logs

script:
  - cd ./tests/
  - phpunit --coverage-clover ../build/logs/clover.xml
  - cd ../

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
